# Generated by Django 6.0.8 on 2026-10-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(blank=True, upload_to="imports/%Y/%m/"),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_sha256", models.CharField(db_index=True, max_length=64)),
                ("source_sheet", models.CharField(blank=True, max_length=120)),
                ("status_column", models.CharField(blank=True, max_length=255)),
                ("source_columns", models.JSONField(default=list)),
                ("snapshot_date", models.DateField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("partial", "Completed with unresolved rows"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=16,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("unique_servers", models.PositiveIntegerField(default=0)),
                ("missing_hostname_rows", models.PositiveIntegerField(default=0)),
                ("missing_ip_rows", models.PositiveIntegerField(default=0)),
                ("duplicate_rows", models.PositiveIntegerField(default=0)),
                ("conflicting_server_groups", models.PositiveIntegerField(default=0)),
                ("non_advancing_server_groups", models.PositiveIntegerField(default=0)),
                ("unmapped_status_rows", models.PositiveIntegerField(default=0)),
                ("warning", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imports",
                        to="website.parameter",
                    ),
                ),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=255)),
                ("normalized_hostname", models.CharField(max_length=255, unique=True)),
                ("current_ip", models.CharField(blank=True, max_length=100)),
                ("ip_ambiguous", models.BooleanField(default=False)),
                ("operating_system", models.CharField(blank=True, max_length=150)),
                ("environment", models.CharField(blank=True, max_length=100)),
                ("first_seen_on", models.DateField(blank=True, null=True)),
                ("last_seen_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["hostname"],
                "indexes": [
                    models.Index(
                        fields=["hostname"], name="website_ser_hostnam_721373_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_row", models.PositiveIntegerField()),
                (
                    "hostname",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "ip_address",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("operating_system", models.CharField(blank=True, max_length=150)),
                ("environment", models.CharField(blank=True, max_length=100)),
                ("raw_status", models.CharField(blank=True, max_length=255)),
                (
                    "mapped_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("not_applicable", "Not Applicable"),
                            ("unmapped", "Unmapped"),
                        ],
                        default="unmapped",
                        max_length=20,
                    ),
                ),
                ("source_data", models.JSONField(default=dict)),
                ("duplicate_row", models.BooleanField(default=False)),
                ("issue", models.CharField(blank=True, max_length=255)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="website.importbatch",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_records",
                        to="website.server",
                    ),
                ),
            ],
            options={
                "ordering": ["source_row"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("not_applicable", "Not Applicable"),
                            ("unmapped", "Unmapped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_status", models.CharField(blank=True, max_length=255)),
                ("observed_on", models.DateField()),
                ("recurrence_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "latest_import",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_states",
                        to="website.importbatch",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="states",
                        to="website.parameter",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="website.server",
                    ),
                ),
            ],
            options={
                "ordering": ["parameter__name", "server__hostname"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=60)),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="website.importbatch",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="website.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("not_applicable", "Not Applicable"),
                            ("unmapped", "Unmapped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("not_applicable", "Not Applicable"),
                            ("unmapped", "Unmapped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("initial", "First recorded status"),
                            ("change", "Status change"),
                            ("recurrence", "Recurring non-compliance"),
                            ("manual", "Manual update"),
                        ],
                        max_length=16,
                    ),
                ),
                ("event_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_events",
                        to="website.importbatch",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_events",
                        to="website.parameter",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="website.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["parameter", "snapshot_date"],
                name="website_imp_paramet_05687a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importrecord",
            index=models.Index(
                fields=["batch", "server"], name="website_imp_batch_i_17be7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancestate",
            index=models.Index(
                fields=["status", "parameter"], name="website_com_status_92930e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="compliancestate",
            constraint=models.UniqueConstraint(
                fields=("server", "parameter"), name="unique_server_parameter_state"
            ),
        ),
        migrations.AddIndex(
            model_name="statusevent",
            index=models.Index(
                fields=["server", "parameter", "event_date"],
                name="website_sta_server__b3c5a1_idx",
            ),
        ),
    ]
