# Generated by Django 6.0.8 on 2026-10-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_seed_dashboard_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="sync_target_path",
            field=models.CharField(
                blank=True,
                help_text="Optional local workbook updated when a source row is edited in the web app.",
                max_length=1024,
            ),
        ),
    ]
