# Generated by Django 6.0.8 on 2026-10-02 21:25

from django.db import migrations, models


def backfill_working_copy(apps, schema_editor):
    ImportBatch = apps.get_model("website", "ImportBatch")
    for batch in ImportBatch.objects.exclude(source_file="").iterator():
        batch.working_file = batch.source_file.name
        batch.working_sha256 = batch.file_sha256
        batch.save(update_fields=["working_file", "working_sha256"])


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_importbatch_sync_target_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="working_file",
            field=models.FileField(blank=True, upload_to="imports/edited/"),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="working_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(backfill_working_copy, migrations.RunPython.noop),
    ]
