# Generated by Django 6.0.8 on 2026-10-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_importbatch_working_file_importbatch_working_sha256"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=32, unique=True)),
                ("can_read", models.BooleanField(default=False)),
                ("can_write", models.BooleanField(default=False)),
                ("can_execute", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("granted_by", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["user_id"],
            },
        ),
    ]
