# Generated by Django 6.0.8 on 2026-10-03 07:45

import django.db.models.deletion
from django.db import migrations, models


def rename_master_parameters(apps, schema_editor):
    Parameter = apps.get_model("website", "Parameter")
    database = schema_editor.connection.alias
    for old_name, new_name in (("CrowdStrike", "CS (Craft)"), ("Snow", "SNOW")):
        old = Parameter.objects.using(database).filter(name=old_name).first()
        if old and Parameter.objects.using(database).filter(name=new_name).exists():
            raise RuntimeError(f"Both '{old_name}' and '{new_name}' parameters exist; merge them before renaming.")
        if old:
            old.name = new_name
            old.save(update_fields=["name"])


def reverse_master_parameters(apps, schema_editor):
    Parameter = apps.get_model("website", "Parameter")
    database = schema_editor.connection.alias
    for new_name, old_name in (("CS (Craft)", "CrowdStrike"), ("SNOW", "Snow")):
        current = Parameter.objects.using(database).filter(name=new_name).first()
        if current and Parameter.objects.using(database).filter(name=old_name).exists():
            raise RuntimeError(f"Both '{new_name}' and '{old_name}' parameters exist; merge them before reverting.")
        if current:
            current.name = old_name
            current.save(update_fields=["name"])

class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_parameter_names_tgim_qualys"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="is_current_source",
            field=models.BooleanField(
                default=True,
                help_text="Whether this import belongs to the currently selected workbook data source.",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="is_master_source",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="MasterWorkbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=1024)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                ("parameter_names", models.JSONField(default=list)),
                ("roster_count", models.PositiveIntegerField(default=0)),
                (
                    "previous_roster_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "new_server_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "baseline_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="master_baselines",
                        to="website.importbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "master workbook",
            },
        ),
        migrations.RunPython(rename_master_parameters, reverse_master_parameters),
    ]
